const { test, expect, chromium } = require('@playwright/test');

const publicRoutes = [
  '/',
  '/contact',
  '/privacy',
  '/terms',
  '/feed',
  '/posts/not-a-real-post',
  '/posts/not-a-real-post/comments',
  '/auth/sign-in',
  '/auth/sign-up',
  '/auth/forgot-password',
  '/auth/update-password',
  '/auth/callback',
];
const protectedRoutes = [
  '/admin',
  '/admin/reports',
  '/admin/templates',
  '/communities',
  '/communities/new',
  '/communities/not-a-real-community',
  '/dashboard',
  '/dashboard/create-journal',
  '/journals',
  '/journals/not-a-real-journal',
  '/journals/not-a-real-journal/edit',
  '/journals/not-a-real-journal/settings',
  '/messages',
  '/messages/new',
  '/messages/not-a-real-message',
  '/notes',
  '/notes/not-a-real-note',
  '/notifications',
  '/search',
  '/settings',
  '/settings/billing',
  '/settings/profile',
  '/stories/new',
  '/studio',
  '/studio/admin',
  '/studio/sounds',
  '/studio/templates',
  '/studio/video',
  '/videos',
  '/u/not-a-real-user',
  '/users/not-a-real-user/followers',
  '/users/not-a-real-user/following',
];
const apiRoutes = [
  '/api/billing/checkout',
  '/api/billing/webhook',
  '/api/gifs',
  '/api/live/end',
  '/api/push/send',
  '/api/stock/videos',
  '/api/studio/import-sounds',
  '/api/studio/jamendo',
  '/api/studio/sounds',
  '/api/studio/stock-videos',
  '/api/video/ai',
  '/api/video/cloudinary',
];
const utilityRoutes=['/sitemap.xml','/robots.txt','/manifest.webmanifest'];
const target='https://enotes-amber.vercel.app';

async function verifyPage(page, route, expected) {
  const errors=[];
  page.on('pageerror',e=>errors.push('pageerror: '+e.message));
  page.on('console',m=>{ if(m.type()==='error') errors.push('console: '+m.text()); });
  page.on('requestfailed',r=>errors.push('requestfailed: '+r.url()+' '+(r.failure()?.errorText||'unknown')));
  const response=await page.goto(target+route,{waitUntil:'domcontentloaded',timeout:10000}).catch(()=>null);
  await page.waitForTimeout(250);
  const status=response?.status()||0;
  const final=new URL(page.url());
  const signin=final.pathname==='/auth/sign-in';
  if(expected==='public'){
    expect(signin, route+' unexpectedly auth-gated').toBeFalsy();
    expect(status,'server error for '+route).toBeLessThan(500);
  } else {
    expect(signin && final.searchParams.get('redirect')===route, route+' did not redirect with exact redirect param; got '+page.url()).toBeTruthy();
  }
  if(errors.length) {
    // Ignore aborted requests generated by rapid navigation; page errors and console errors are retained.
    const real=errors.filter(x=>!x.includes('ERR_ABORTED'));
    expect(real, route+' emitted browser errors').toEqual([]);
  }
}

for(const viewport of [{name:'desktop',width:1440,height:900},{name:'mobile',width:390,height:844}]){
  test.describe(viewport.name,()=>{
    test('all public routes',async()=>{
      const browser=await chromium.launch();
      const context=await browser.newContext({viewport});
      const page=await context.newPage();
      for(const route of publicRoutes) await verifyPage(page,route,'public');
      await context.close(); await browser.close();
    });
    test('all protected routes including journal pages',async()=>{
      const browser=await chromium.launch();
      const context=await browser.newContext({viewport});
      const page=await context.newPage();
      for(const route of protectedRoutes) await verifyPage(page,route,'protected');
      await context.close(); await browser.close();
    });
    test('utility files and unauthenticated APIs',async()=>{
      const browser=await chromium.launch();
      const context=await browser.newContext({viewport});
      const page=await context.newPage();
      for(const route of utilityRoutes){
        const response=await page.goto(target+route,{waitUntil:'domcontentloaded',timeout:10000}).catch(()=>null);
        const status=response?.status()||0;
        expect(status,'utility route '+route+' returned server error').toBeLessThan(500);
      }
      for(const route of apiRoutes){
        const response=await page.request.get(target+route,{timeout:10000}).catch(()=>null);
        const status=response?.status()||0;
        expect(status,'API '+route+' returned 5xx').toBeLessThan(500);
      }
      await context.close(); await browser.close();
    });
    test('careless auth interaction and reload',async()=>{
      const browser=await chromium.launch();
      const context=await browser.newContext({viewport});
      const page=await context.newPage();
      await page.goto(target+'/auth/sign-in',{waitUntil:'domcontentloaded',timeout:10000});
      await page.locator('input[type=email]').fill('bad');
      await page.locator('form button[type=submit]').click().catch(()=>{});
      await page.locator('input[type=email]').fill('playtest.invalid.20261004@example.invalid');
      await page.locator('input[type=password]').fill('wrong-password');
      await Promise.all([
        page.locator('form button[type=submit]').click().catch(()=>{}),
        page.locator('form button[type=submit]').click().catch(()=>{}),
        page.locator('form button[type=submit]').click().catch(()=>{}),
      ]);
      await page.waitForTimeout(500);
      await page.reload({waitUntil:'domcontentloaded',timeout:10000});
      await page.reload({waitUntil:'domcontentloaded',timeout:10000});
      await expect(page.locator('input[type=email]')).toBeVisible();
      await context.close(); await browser.close();
    });
  });
}
